/// Flutter icons BloodDonation
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BloodDonation
///      fonts:
///       - asset: fonts/BloodDonation.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class BloodDonation {
  BloodDonation._();

  static const _kFontFam = 'BloodDonation';
  static const String _kFontPkg = null;

  static const IconData phone_android = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_forwarded = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watch = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData build = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_1 = IconData(0xf1e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_control_phone = IconData(0xf2a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
